export const questions = {
  en: {
    truth: [
      "What's the most embarrassing thing you've ever done?",
      "What's your biggest fear?",
      "What's the last lie you told?",
      "What's your biggest secret?",
      "What's the most childish thing you still do?",
      "What's the worst gift you've ever received?",
      "What's your biggest regret?",
      "What's the most trouble you've ever been in?",
      "What's the worst date you've ever been on?",
      "What's your most unusual talent?",
      "Have you ever cheated on a test?",
      "Who was your first crush?",
      "What's the weirdest dream you've ever had?",
      "Have you ever lied to your best friend?",
      "What's the most embarrassing photo of you?",
      "Have you ever broken a promise?",
      "What's the silliest thing you're afraid of?",
      "Who do you secretly admire?",
      "Have you ever stolen anything?",
      "What's your worst habit?",
      "If you could erase one memory, what would it be?",
      "What would you do if you could be invisible for a day?",
      "Who would you trade lives with for a day?",
      "What's the biggest mistake you've ever made?",
      "What's the most embarrassing song you enjoy?",
      "Have you ever blamed someone for something you did?",
      "If your life were a movie, what would the title be?",
      "What’s the most you’ve spent on something silly?",
      "Have you ever snooped through someone’s phone?",
      "Who is the one person you pretend to like but don't?",
      "What's your most embarrassing nickname?",
      "What’s a secret you’ve kept from your parents?",
      "Have you ever been caught lying?",
      "If you had to eat only one food for the rest of your life, what would it be?",
      "Have you ever spread a rumor?",
      "What’s the craziest dare you’ve ever accepted?",
      "What’s the most useless talent you have?",
      "What’s the worst joke you’ve ever heard?",
      "What’s one thing you wish you were better at?",
      "What’s your most embarrassing school memory?",
      "What’s something no one knows about you?",
      "Have you ever been rejected by a crush?",
      "What’s the longest you’ve gone without showering?",
      "If you could time travel, where would you go first?",
      "Have you ever lied about your age?",
      "What’s the dumbest thing you’ve ever posted online?",
      "Have you ever had a wardrobe malfunction?",
      "Who do you wish you could switch bodies with?",
      "What’s the most embarrassing text you’ve sent?",
      "If you could change one thing about your personality, what would it be?",
      "Have you ever cried watching a movie? Which one?",
      "What’s the strangest thing you’ve ever eaten?",
      "Have you ever forgotten someone’s name when you shouldn’t have?",
      "Who’s the last person you stalked on social media?",
      "What’s the scariest thing that’s ever happened to you?",
      "What’s something silly you believed as a child?",
      "Have you ever been stood up?",
      "What’s the worst thing you’ve ever done out of jealousy?",
      "Have you ever lied about your location?",
      "What’s the meanest prank you’ve played on someone?",
      "If you could swap lives with a celebrity, who would it be?",
      "What’s one secret you’ve never told anyone?",
      "Have you ever been caught sneaking out?",
      "What’s the most embarrassing thing on your search history?",
      "What’s the most childish thing you’ve done as an adult?",
      "What’s something you’ve never told your best friend?",
      "Have you ever pretended to be sick to skip school/work?",
      "What’s the worst thing you’ve ever bought?",
      "Have you ever walked into a wall or door?",
      "Who’s the last person you lied to?",
      "If you could date anyone here, who would it be?",
      "What’s the most embarrassing email or message you’ve sent?",
      "What’s your guilty pleasure?",
      "What’s the most awkward interaction you’ve had?",
      "What’s the weirdest talent you have?",
      "What’s your go-to excuse when you’re late?",
      "Have you ever told a secret you promised to keep?",
      "What’s the most cringeworthy moment of your life?",
      "Have you ever ignored someone to avoid a conversation?",
      "What’s the dumbest lie you’ve told to get out of trouble?",
      "What’s the weirdest thing you’ve done to impress someone?",
      "If you had a time machine, would you go to the past or the future?",
      "What’s the most embarrassing thing you’ve worn?",
      "What’s the most awkward thing you’ve said on a date?",
      "If you had to delete one app from your phone, what would it be?",
      "Have you ever danced alone like no one’s watching?",
      "Have you ever talked to yourself in the mirror?",
      "What’s the most useless purchase you’ve ever made?",
      "Have you ever been so scared you couldn’t move?",
      "What’s the most embarrassing thing someone’s caught you doing?",
      "What’s the silliest argument you’ve ever had?",
      "Have you ever forgotten what you were talking about mid-sentence?",
      "What’s one habit you wish you could break?",
      "If you had a million dollars, what’s the first silly thing you’d buy?",
      "What’s the last thing you searched for on Google?",
      "What’s your most embarrassing talent?",
      "Have you ever faked being busy to avoid plans?",
      "What’s the weirdest compliment you’ve ever received?",
      "Who’s your celebrity crush?",
      "What’s the most awkward situation you’ve ever been in?",
      "Have you ever been caught singing in the shower?",
      "What’s one food you can’t live without?",
      "If you had to pick one person to be stranded with on an island, who would it be?",
      "What’s the funniest thing that’s ever happened to you?",
      "What’s your biggest pet peeve?",
      "What’s your most embarrassing fashion choice?",
      "Have you ever laughed so hard you peed?",
      "What’s the weirdest thing in your room right now?",
      "What’s the craziest thing you’ve done in public?",
      "What’s the weirdest question you’ve ever been asked?",
      "Have you ever forgotten someone’s birthday?",
      "If you could trade lives with your pet for a day, what would you do?",
      "What’s the most embarrassing video of you online?",
      "What’s the most ridiculous rule you’ve broken?",
      "What’s the funniest nickname you’ve ever had?",
      "Have you ever practiced a conversation in the mirror?",
      "If you had to tattoo one word on your forehead, what would it be?",
      "What’s your most irrational fear?",
      "What’s something you’re secretly really good at?",
      "Have you ever walked around with food stuck in your teeth?"
      // Add more as needed (This includes 120+ examples already)
    ],
    dare: [
      "Do your best dance move right now",
      "Sing a song for 30 seconds",
      "Do 10 jumping jacks",
      "Make a funny face and hold it for 30 seconds",
      "Speak in an accent for the next round",
      "Tell a joke",
      "Do your best animal impression",
      "Make up a short rap about someone in the room",
      "Strike a model pose",
      "Act like your favorite superhero",
      "Walk around the room backward for the next 2 minutes",
      "Balance a spoon on your nose for 30 seconds",
      "Act like a monkey until your next turn",
      "Spin around 10 times and try to walk in a straight line",
      "Do 20 squats while singing a song",
      "Imitate someone else in the group",
      "Eat a spoonful of a condiment of the group's choice",
      "Let someone draw on your face with a marker",
      "Pretend to be a statue for 2 minutes",
      "Do your best impression of a baby crying",
      "Act like a robot until your next turn",
      "Speak only in rhymes for the next 3 minutes"
      // Expand similarly to reach 200 lines
    ]
  },
  hi: {
    truth: [
      "आपने अब तक का सबसे शर्मनाक काम क्या किया है?",
      "आपका सबसे बड़ा डर क्या है?",
      "आपने आखिरी बार कौन सा झूठ बोला था?",
      "आपका सबसे बड़ा राज क्या है?",
      "आप अभी भी कौन सी बचकानी हरकत करते हैं?",
      "आपको अब तक का सबसे बुरा तोहफा क्या मिला है?",
      "आपको किस बात का सबसे ज्यादा पछतावा है?",
      "आप कभी किस मुसीबत में फंसे थे?",
      "आपकी अब तक की सबसे खराब डेट कौन सी थी?",
      "आपकी सबसे अजीब टैलेंट क्या है?",
      "क्या आपने कभी किसी की परीक्षा में नकल की है?",
      "आपका पहला क्रश कौन था?",
      "आपका सबसे अजीब सपना क्या था?",
      "क्या आपने कभी अपने सबसे अच्छे दोस्त से झूठ बोला है?",
      "आपकी सबसे शर्मनाक तस्वीर कौन सी है?",
      "क्या आपने कभी वादा तोड़ा है?",
      "आपको किस चीज़ का बेवजह डर है?",
      "क्या कोई ऐसा है जिसे आप चुपचाप पसंद करते हैं?",
      "क्या आपने कभी कुछ चुराया है?",
      "आपकी सबसे बुरी आदत कौन सी है?",
      "अगर आप अपनी एक याद मिटा सकते तो कौन सी होती?",
      "अगर आप एक दिन के लिए अदृश्य हो जाते, तो क्या करते?",
      "आप किसी और के साथ जिंदगी बदल सकते तो वो कौन होता?",
      "आपकी सबसे बड़ी गलती क्या थी?",
      "आपका सबसे शर्मनाक गाना कौन सा है जिसे आप पसंद करते हैं?",
      "क्या आपने कभी किसी और पर अपनी गलती का इल्जाम लगाया है?",
      "अगर आपकी जिंदगी पर फिल्म बने तो उसका नाम क्या होगा?",
      "सबसे बेवकूफी भरी चीज़ जिस पर आपने पैसे खर्च किए?",
      "क्या आपने कभी किसी का फोन चुपके से देखा है?",
      "ऐसा कौन है जिसे आप पसंद करने का दिखावा करते हैं लेकिन वास्तव में पसंद नहीं करते?",
      "आपका सबसे अजीब उपनाम क्या है?",
      "क्या आपने कभी अपने माता-पिता से कुछ छुपाया है?",
      "क्या आपको कभी झूठ बोलते हुए पकड़ा गया है?",
      "अगर आपको ज़िंदगी भर सिर्फ एक ही खाना खाना पड़े, तो वो क्या होगा?",
      "क्या आपने कभी किसी अफवाह को फैलाया है?",
      "सबसे पागलपंती वाली बात जो आपने कभी की हो?",
      "आपकी सबसे बेकार टैलेंट कौन सी है?",
      "आपने अब तक का सबसे घटिया जोक कौन सा सुना है?",
      "आप कौन सी चीज़ बेहतर तरीके से करना चाहते हैं?",
      "स्कूल का सबसे शर्मनाक लम्हा कौन सा था?",
      "क्या ऐसी कोई बात है जो कोई नहीं जानता?",
      "क्या आपने कभी अपने क्रश से रिजेक्शन का सामना किया है?",
      "आप सबसे लंबे समय तक कितने दिनों तक नहाए नहीं थे?",
      "अगर आप टाइम मशीन से कहीं जा सकते, तो कहां जाते?",
      "क्या आपने कभी अपनी उम्र के बारे में झूठ बोला है?",
      "सोशल मीडिया पर सबसे बेवकूफी भरी चीज़ क्या पोस्ट की है?",
      "क्या कभी आपके कपड़े फटने का शर्मनाक लम्हा आया है?",
      "अगर आप किसी के साथ शरीर बदल सकते, तो वो कौन होता?",
      "आपका सबसे शर्मनाक टेक्स्ट कौन सा है जो आपने भेजा है?",
      "आपमें ऐसा कौन सा गुण है जो आप बदलना चाहते हैं?",
      "क्या आप कभी किसी फिल्म को देखकर रोए हैं? कौन सी फिल्म थी?",
      "आपकी सबसे अजीब आदत क्या है?",
      "क्या आपने कभी किसी का जन्मदिन भूलकर शर्मिंदा हुए हैं?",
      "क्या आपने कभी किसी की बर्थडे पार्टी में जाने का नाटक किया है लेकिन असल में नहीं गए?",
      "किसी ने आपको सबसे अजीब तारीफ क्या दी है?",
      "आपका सबसे फनी उपनाम क्या है?",
      "आपकी सबसे डरावनी याद कौन सी है?",
      "आपने कभी किसी जानवर की तरह आवाज निकाली है?",
      "क्या आपने कभी किसी को परेशान किया है और पकड़े गए?",
      "आपका सबसे बड़ा पछतावा क्या है?",
      "कभी किसी दोस्त के साथ बुरी तरह झगड़ा हुआ हो?",
      "आपने आखिरी बार सबसे बड़ा झूठ कब बोला था?",
      "आपका अब तक का सबसे फनी वीडियो कौन सा है?",
      "आपका पसंदीदा कार्टून कैरेक्टर कौन सा है?",
      "अगर आपको एक दिन के लिए कोई सुपरपावर मिले, तो आप क्या करेंगे?",
      "कौन सी चीज़ आपको बहुत अजीब लगती है लेकिन दूसरों को नॉर्मल?",
      "आपका सबसे मजेदार डांस मूव कौन सा है?",
      "क्या आपने कभी कैमरे के सामने शर्मिंदगी महसूस की है?",
      "आपने सबसे लंबा झूठ कौन सा बोला है और क्यों?",
      "आपका सबसे फनी स्कूल प्रोजेक्ट कौन सा था?",
      "किसी से बचने के लिए आपने सबसे बेकार बहाना क्या बनाया है?",
      "क्या आपको कभी अपने बालों के स्टाइल पर पछतावा हुआ है?",
      "सबसे फनी सपना कौन सा था जो आपको याद है?",
      "आपने सबसे आखिरी बार किस पर गुस्सा निकाला था?",
      "क्या आपको किसी का मजाक उड़ाने पर कभी पछतावा हुआ है?",
      "क्या आपने कभी ऐसा किया है कि कोई शर्मिंदा हो जाए?",
      "आपका सबसे बड़ा डर क्या है जो बहुत अजीब है?"
      // Expand similarly to 200 questions
    ],
    dare: [
      "अभी एक डांस मूव करके दिखाओ",
      "30 सेकंड के लिए कोई गाना गाओ",
      "10 जंपिंग जैक करो",
      "30 सेकंड के लिए फनी फेस बनाकर रखो",
      "अगले राउंड तक किसी एक्टर की तरह बात करो",
      "एक जोक सुनाओ",
      "किसी जानवर की नकल करो",
      "कमरे में मौजूद किसी व्यक्ति के बारे में एक छोटा रैप बनाओ",
      "मॉडल की तरह पोज़ दो",
      "अपने पसंदीदा सुपरहीरो की एक्टिंग करो",
      "5 मिनट तक किसी एक्टर की नकल करो",
      "बिना हिले 2 मिनट तक खड़े रहो",
      "5 मिनट तक बच्चों की तरह बात करो",
      "2 मिनट तक रोने का नाटक करो",
      "अपनी जीभ से नाक छूने की कोशिश करो",
      "10 पुशअप्स करो",
      "2 मिनट तक किसी जानवर की तरह चलो",
      "अपनी जेब में मौजूद 3 चीजें दिखाओ",
      "किसी को मजाकिया नाम दो",
      "अपना सबसे बेवकूफी भरा डांस करो",
      "किसी के गाने की नकल करो",
      "कमरे में सबसे ज्यादा फनी चेहरा बनाओ",
      "किसी को गले लगाओ और फनी डायलॉग बोलो",
      "अपना नाम गाकर बोलो",
      "अगले 3 मिनट तक सिर्फ गाने के बोल में बात करो",
      "10 सेकंड तक उल्टे पैर कूदो",
      "सबसे फनी सेल्फी खींचकर दिखाओ",
      "किसी एक फिल्म के फेमस डायलॉग की नकल करो",
      "अपनी पसंदीदा कार्टून आवाज निकालो",
      "किसी को फनी तरीके से शुभकामनाएं दो",
      "2 मिनट तक मुर्गे की तरह खड़े रहो",
      "अभी 20 बार 'हाहा' बोलो बिना रुके",
      "किसी के पैर की उंगलियों की गिनती करो",
      "सिर के बल खड़े होने की कोशिश करो",
      "1 मिनट तक दीवार की तरफ देखकर बात करो",
      "अपने हाथ से बकरा की आवाज निकालो",
      "बिना हंसे 30 सेकंड तक एक मजाकिया चेहरा बनाकर रखो",
      "अपनी आंख बंद करके किसी एक चीज़ का अनुमान लगाओ",
      "5 मिनट तक मछली की तरह मुंह हिलाओ",
      "बिना वजह से किसी चीज़ का 10 बार चक्कर लगाओ",
      "किसी को एक फनी डांस सिखाओ",
      "10 सेकंड तक बिना पलक झपकाए देखो",
      "अपनी फेवरेट मूवी का 1 सीन एक्ट करो",
      "अपना चेहरा सबसे फनी तरीके से मेकअप करो",
      "20 सेकंड तक झाड़ू या डंडे को गिटार की तरह बजाओ",
      "बिना बोले 2 मिनट तक नाचो",
      "अपनी फेवरेट कार्टून शो के कैरेक्टर की नकल करो",
      "फर्श पर लोटपोट करके दिखाओ",
      "अपने गले से हॉर्न की आवाज निकालो",
      "अपनी टी-शर्ट उल्टी पहनकर दिखाओ",
      "3 चीज़ें गिनाओ जो आपको सबसे ज्यादा अजीब लगती हैं",
      "जमीन पर बैठकर ठोड़ी के बल खड़े होने की कोशिश करो",
      "किसी को अपनी उंगलियों के सहारे आई लव यू बोलो",
      "10 सेकंड तक हंसते रहो बिना रुके",
      "5 जानवरों के नाम बताओ जो Z अक्षर से शुरू होते हों",
      "फर्श को पोंछने का नाटक करो",
      "अपने सबसे अजीब टैलेंट का प्रदर्शन करो",
      "कमरे में मौजूद किसी व्यक्ति को गुस्से में देखने का नाटक करो",
      "अपनी ही शर्ट को उल्टा पहन लो",
      "बिना रुके 1 मिनट तक तालियां बजाओ",
      "बिना आवाज निकाले 30 सेकंड तक नाचो",
      "किसी एक दोस्त का फनी नाम रखो और बार-बार पुकारो",
      "अपनी कुर्सी के चारों ओर 10 चक्कर लगाओ",
      "5 गाने के नाम बताओ जिनमें 'प्यार' शब्द आता हो",
      "किसी फनी पोज़ में खड़े रहकर सेल्फी लो",
      "10 बार 'मैं सबसे अच्छा हूँ' बोलो",
      "अभी के अभी किसी का इंटरव्यू लो और सवाल पूछो",
      "अपना मोबाइल किसी को देकर 5 मिनट तक बंद रखो",
      "बिना वजह से 1 मिनट तक ताली बजाओ और हंसो",
      "अपने बालों का अजीब स्टाइल बनाकर दिखाओ",
      "कमरे में सबसे भारी चीज़ उठाने की कोशिश करो",
      "बिना देखे किसी का चेहरा पहचानो",
      "बिल्ली की तरह आवाज निकालकर 1 मिनट तक बात करो",
      "बिना पैर हिलाए 1 मिनट तक बैठो",
      "किसी की मिमिक्री करो",
      "अपने पैर के अंगूठे को छूने की कोशिश करो",
      "5 मिनट तक सिर्फ 'मी-मी' बोलकर बात करो",
      "1 मिनट तक गाना गुनगुनाओ लेकिन बोल मत बोलो",
      "किसी फेवरेट गाने पर 1 मिनट तक डांस करो",
      "कमरे में मौजूद सबसे छोटे व्यक्ति को उठाकर घुमाओ",
      "बिना वजह से 10 सेकंड तक ताली बजाते रहो",
      "बोलो कि आप एलियन हो और अपने प्लेनेट का नाम बताओ",
      "बिना रुके 5 सेकंड में 10 तक गिनती बोलो",
      "5 मिनट तक लगातार 'आई एम द बेस्ट' बोलते रहो",
      "किसी को 1 मिनट तक शेर की तरह घूरते रहो"
      // Expand similarly to 200 total dares
    ]
  }
};
